### ISSUE TITLE
Error: _docs folder is not handled correctly

### ISSUE THREAD

**Issue by DoomyTheFroomy** [jo/couchdb-compile#17]
When trying to push/compile a `_docs` folder it is still part of the `_design` document. The couchdb will answer with an corresponding error: 

```js
{ [Error: Bad special document member: _docs]
  name: 'Error',
  error: 'doc_validation',
  reason: 'Bad special document member: _docs',
  scope: 'couch',
  statusCode: 500,
  request: {...},
  headers: 
   { date: 'Thu, 08 Oct 2015 09:51:28 GMT',
     'content-type': 'application/json',
     'cache-control': 'must-revalidate',
     statusCode: 500,
     uri: '..'    
  },
  errid: 'non_200',
  description: 'couch returned 500' 
}
```

My folder structure is close to, the one that is described in [couchapp wiki](https://github.com/couchapp/couchapp/wiki/Complete-Filesystem-to-Design-Doc-Mapping-Example): 

    myapp/
      _attachments/
        images/
          logo.png
      _docs/
        sample.json
        doc_needing_encoding/
          _id (the ID for the document as text on the first line of this file)
          title (same as ID, just for the title field. Repeat pattern as needed)
          content.html (HTML content that will be encoded when it's added to the JSON doc)
      lists/
        xml.js
      rewrites.js
      shows/
        preview.js
        xml.js
      updates/
        in-place.js
      views/
        foobar/
          map.js
          reduce.js
      validate_doc_update.js

I'm not sure if this should be part of couchdb-compile or couchdb-push.

**Comment by jo** [comment]
couchdb-compile is not 100% compatible to Erica or the Python couchapp tool and this is so by intention. couchdb-compile is much simpler and has left out the mappings which are not directly mirrored by the JSON structure of the according (design) document.

couchdb-push (and couchdb-compile) does not care if its a design doc or not and can also handle plain JSON documents (and even JavaScript modules). Therefore you can use it to push your `sample.json` directly.

**Comment by jo** [comment]
I added a note in the [Couchapp wiki](https://github.com/couchapp/couchapp/wiki/Complete-Filesystem-to-Design-Doc-Mapping-Example#systems-support-this-format)
