### ISSUE TITLE
Support index.js

### ISSUE THREAD

**Issue by jo** [jo/couchdb-compile#7]
For node modules you can `require('myapp')` and it will load `myapp/index.js` if present. CouchDB Compile should support that, too

**Comment by jo** [comment]
done

**Comment by BigBlueHat** [comment]
I'm storing some CommonJS style code in .js files that I want inside the JSON files stored in CouchDB--think pastebin, etc.

This makes it impossible to push those as it assumes they are meant to be turned into JSON docs--leveraging the local build-time require system--vs. used by some other build system (browserify, etc), or even left in place for use in CouchDB's CommonJS implementation.

Would you mind reverting this change and/or explaining what the goal is?

The test looks like it's just a short-hand method of including some common JSON among files...maybe?

Thanks!

**Comment by jo** [comment]
I explained the use case here: http://docs.ehealthafrica.org/couchdb-best-practices/#commonjs-modules-%28aka-node-modules%29

But I see your point. (Note that only files called `index.js` are considered CommonJS modules) Would an API option and a switch for the CLI  to disable the `index.js` examination solve that problem?

**Comment by BigBlueHat** [comment]
Ah. Thanks for the context! :smile: I figured there was a good one. :smiley: 

I think a CLI switch or config setting to either enable it would be best. Having it off by default means that folks could simply `npm install couchdb-push` and then successfully push any old CouchApp folder (assuming it matches the filesystem layout spec)--even if they happen to use index.js in a doc (as I had).

The promise of writing tests for map/reduce, etc. outside of CouchDB is fabulous, though, so keeping it available is important for those that want to use it.

Seem reasonable? :smile:

**Comment by jo** [comment]
yes, will go that route :)
